### PR TITLE
[WIP] TSO JWebbinar 

### PR DESCRIPTION
**Pull request by nespinoza**
Hi everyone,

 Here's a work-in-progress PR on one of the JWebbinar notebooks --- the "Exploring TSO products" one. 

 This has to date (Nov 19):

 - The `requirements.txt`.
 - A close-to-finished notebook. Still missing some final pieces that I intend to work later on, but before Monday.

N.

### CODE REVIEW

**Comment by skendrew** [comment]
I checked the requirements file and this is fine for me. I don't think I need a separate requirements file for my notebook. I'll create a draft notebook as well and create a separate pull request.

**Comment by skendrew** [comment]
By the way @nespinoza this should be notebook 3 no? Notebook 2 is the one I will do, iirc?

**Comment by nespinoza** [comment]
So, there's three parts to the JWebbinar, but the first one is just an introduction. So only the second and third parts have a notebook --- yours would then be notebook number 1, and mine 2. Right? :D

**Comment by skendrew** [comment]
ok yes that makes sense!

**Pull request merged**
