### PR TITLE
Adding cubeviz demo

### PR DESCRIPTION
**Pull request by bmorris3**
Fun with Cubeviz, MIRI, black holes, astropy units, and more. ⚫

### CODE REVIEW

**Comment by camipacifici** [comment]
Is the notebook pulling from MAST? If so, can you get the file to Manuel and pull from the platform please?
Do you want to keep the old notebook or shall we not load it on the platform?

**Comment by bmorris3** [comment]
That's right @camipacifici, I wanted to ask how to load from the platform correctly – do we use the Box link we created for Manuel, like [this Mosviz demo](https://github.com/spacetelescope/jwebbinar_prep/blob/main/jdaviz_2023/Jwebbinar24MosvizDemo.ipynb)? The only other notebook to compare with is [the Imviz notebook](https://github.com/spacetelescope/jwebbinar_prep/blob/main/jdaviz_2023/imviz_rose_demo.ipynb), and I see Pey-Lian isn't using MAST.

**Comment by camipacifici** [comment]
Yes, what Pey Lian is doing is the correct way! Thank you!

**Comment by bmorris3** [comment]
Got it, done in [16d5bc9](https://github.com/spacetelescope/jwebbinar_prep/pull/135/commits/16d5bc946c1dadbc186c972d6b977e9acbada3e3), @camipacifici 👍🏻

**Pull request merged**
