### PR TITLE
Add new method to load MOS data by directory and point to Box data

### PR DESCRIPTION
**Pull request by PatrickOgle**
For review.

### CODE REVIEW

**Comment by PatrickOgle** [comment]
@ojustino I assume you mean jwebbinar_prep, not dat_pyinthesky in your comment above?

**Comment by PatrickOgle** [comment]
@ojustino @camipacifici Resolved all technical review comments.  However, the simulated data for this notebook are not yet public.  Should we:
1) Delete the box filename from the notebook
or
2) Simply not publish the notebook until the data are public?

**Comment by PatrickOgle** [comment]
@ojustino  I updated the notebook and requirements to follow your technical review suggestions.   Please test with any MOS dataset, or I can give you a private dataset for further testing, if necessary.

**Comment by ojustino** [comment]
Hi @PatrickOgle, thank you for your edits. You resolved all outstanding issues from my review. I tested by entering a Box link to the data in question and didn't notice any issues.

@camipacifici, we've completed the technical review for this notebook and are ready to merge the changes.

**Comment by camipacifici** [comment]
Great!! Merging now.
Thank you very much!

**Pull request merged**
