### PR TITLE
Specutils notebook for data analysis tools webbinar

### PR DESCRIPTION
**Pull request by eteq**
This is basically a lightly edited version of the specutils notebooks in https://github.com/astropy/astropy-workshop . It may be (probably is?) too long, but I welcome suggestions on what's a good choice to cut!

### CODE REVIEW

**Comment by camipacifici** [comment]
Looks good to me overall! (I have not tested it though)
Two things: 
- can you find some JWST simulated data for this? NIRSpec might be complicated, but we could use a model of some sort.
- if it ends up being too long, you can still skip some sections that are not critical in the workflow.

**Comment by camipacifici** [comment]
@eteq
Tested the notebook, looks good and works fine! A few things still needed:
- Please use the spectrum Patrick provided.
- It would be best to provide a different spectrum for the exercise (we should not expect people will go fish their own on the web).
- Please provide also the "live" version of the notebook that you will use during the webinar.
- Test the notebook on the platform.

**Comment by eteq** [comment]
Alright, I think I've addressed your concerns @camipacifici, although with two caveats:

1. I re-worked the "fish their own" example to give a concrete specific spectrum they can use if they want, but also give the option to get their own.  My thinking here is that some people really have a "favorite object", but you're right for those that don't it makes sense to do a specific example (in this case an SDSS spectrum we know works with specutils).
2. I have *not* split this into the "live" and "not live" version, mainly because I'm now thinking the way to address the "too long" is to treat it as a "choose-your-own-adventure" where after getting through the overview I will have folks pick the thing they are most interested in, in which case there's not much point in having the separate "live" version.  But if you don't like the "choose-your-own-adventure" approach, I can do live as you suggest!

**Comment by camipacifici** [comment]
@eteq, notebook looks very good. Thank you for addressing the changes. 

I am ok with giving the option of getting their favorite spectrum, but we need to be ready for all sort of problems and above all give people enough time to do that exercise. Are you ready for that?

About the "live", I would strongly encourage you to NOT give the choice, but use the same strategy Alicia used: they follow along on the "solution" notebook, typing in only the exercises, and you code live in the empty cells of the "live" version. If this takes too long, you can consider skipping parts of the notebook maybe putting them at the end, to work on in their own time.

Merging this now so you can test it on the platform, but please address my concern about the "live" notebook.

**Comment by eteq** [comment]
> we need to be ready for all sort of problems and above all give people enough time to do that exercise. Are you ready for that?

I *think so*, in that I've done that part in a AAS workshop without too much trouble.  But I think the key is for us to be ready to lean on "hmm, your favorite spectrum might not be working because it's from some random observatory.  Maybe you should just use the SDSS one instead" if it's too much of an issue.  I'll be sure to say that out loud in addition to the text in the exercise.

> About the "live",

Yeah, point taken. (repeating from a discussion we had out-of-band:) The reason for the "choose your own adventure" was because the last 2/3 or so is several different somewhat stand-alone analysis tasks, which then could make it a way to allow people to pick the thing most relevant to them in the limited time available.the reason for the "choose your own adventure" was because the last 2/3 or so is several different somewhat stand-alone analysis tasks, which then could make it a way to allow people to pick the thing most relevant to them in the limited time available.

But in the end I see @camipacifici point so will make a live version and see how long it really takes.  Might have to shrink this down or come up with a more structured "choose your own adventure" if the live version doesn't fit into the time constraints.

**Pull request merged**
