### PR TITLE
Update MRS notebooks

### PR DESCRIPTION
**Pull request by drlaw1558**
Overhauled data handling and file paths to streamline compatibility between JWebbinar and MO versions of notebook/data products.  Now pulls data from Box within the notebook, and revises cache handling structure.  Fix some whitespace.

### CODE REVIEW

**Comment by camipacifici** [comment]
Thank you David.
@ojustino, when you have a look at this, can you please check that the version in branch webbinar5 is not broken now with the files in a different place?

**Comment by ojustino** [comment]
This pull request will resolve #61 once merged.

@camipacifici I was able to run the version in `webbinar5` without issue after changing `cache_dir` and downloading the Box folder. If we modify the data location on Box, we can remember to update the version of `MRS_Notebook2.ipynb` in that branch as well.

**Comment by camipacifici** [comment]
Good, thank you!
Merging now.

**Comment by ojustino** [comment]
I'll retroactively state that `MRS_Notebook2.ipynb` passes the technical review. `MRS_Notebook1.ipynb`had a few more PEP8 warnings that have been addressed in #70.

**Pull request merged**
