### PR TITLE
Add imaging mode notebook

### PR DESCRIPTION
**Pull request by bhilbert4**
Currently in-progress. I'm creating this PR now so that others can view the in-progress notebook and make comments on the general style at an upcoming meeting.

So far I've made edits to the first few steps of calwebb_detector1, up through superbias subtraction.

### CODE REVIEW

**Comment by cslocum** [comment]
image

**Comment by cslocum** [comment]
image

**Comment by eteq** [comment]
NOTE: I just changed the default branch in this repo to `main`. This PR did not get re-assigned to that as its base.  So if/when this gets merged it will need to be ported over to `main` (I can take care of that myself, but will probably need a ping!)

**Comment by bhilbert4** [comment]
@camipacifici the first draft of the notebook for Stage 1 is now more or less complete, and available for review. @karllark I have a placeholder in there for downloading a MIRI simulation and have left it as an exercise to run it through the pipeline, if the MIRI team is interested in that.

**Comment by robelgeda** [comment]
Hi @bhilbert4, there is a Jupyter Lab issue which forces us to use `%matplotlib inline`. If you have plots in your notebook, please use the `matplotlib``inline` option.

**Comment by cslocum** [comment]
Is this PR intended to be included in the first JWebbinar session(s)?  If so, when is it expected to be ready/merged?

**Comment by bhilbert4** [comment]
No, this is for the imaging mode JWebbinar session, to be held towards the end of May.

**Comment by bhilbert4** [comment]
Complete first drafts of notebooks for all three pipeline stages are now present. I still need to get the proper command line call for each pipeline in the cells where I show that. 

I still wonder about how practical it is to run these notebooks in real time. Many of the steps aren't too bad in terms of time, but there are certainly some steps (and by extension, full pipelines) that take long enough to run that it would be awkward to run in real time.  I'm definitely interested to hear what the run times are like in the environment to  be used for the webinars. I've cut down the data about as far as I can. Stage 1 is running on a single file, and Stages 2 and 3 are running on 3 files.

Other than running various steps/pipelines on a potential MIRI dataset, I'm also not sure what useful exercises to include.

**Comment by cslocum** [comment]
Hey Bryan - you should definitely test them out at jwebbinar.science.stsci.edu.  However - they won't be present by default unless you clone/checkout your branch directly.  The content provided by default is that which is the main branch.

**Comment by karllark** [comment]
> Other than running various steps/pipelines on a potential MIRI dataset, I'm also not sure what useful exercises to include.

I am working on getting a good dataset.  Not sure how long this will take, but hopefully will be able to provide something before the JWebbinar.

**Comment by bhilbert4** [comment]
Timing test results running the notebooks on jwebbinar.science.stsci.edu:
Everything runs much faster than it does locally on my laptop, thankfully.

calwebb_detector1: 3 min 15 sec
group_scale: 5 sec
dq_init: 6 sec
saturation: 6 sec
superbias: 5 sec
refpix: 9 sec
linearity: 7 sec
persistence: 16 sec
dark: 13 sec
jump: 10 sec
ramp_fit: 60 sec

image2 pipeline: 38 sec
assign_wcs: 8 sec
flat fielding: 9 sec
photom: 8 sec
resample: 23 sec

image3 pipeline - 90 sec
tweakreg: 23 sec
skymatch: 14 sec
outlier detection: 47 sec
resample: 20 sec
source catalog: 12 sec

**Comment by camipacifici** [comment]
This is great! Thank you, @bhilbert4 !

**Comment by bhilbert4** [comment]
Closing this PR in favor of #16, which points to the correct branch.

**Pull request closed without merging**
