### PR TITLE
Add Specviz JWebbinar notebook

### PR DESCRIPTION
**Pull request by rosteen**
I tried to be fairly detailed in the notebook, in case people who can't make the live session later get access to the notebook. 

Note that this currently uses an SDSS spectrum, as I haven't gotten a nice JWST file to use yet.

### CODE REVIEW

**Comment by rosteen** [comment]
I also imagine I should probably host the file I'm using on Box, right now it pull straight from SDSS.

**Comment by camipacifici** [comment]
Thank you!
Yes, files should be on box. You should have received the invite to the correct folder.

**Comment by rosteen** [comment]
Added the file to the 2_jdat folder where Duy put their data. I created a link and made it viewable by anyone with the link, but when using this code in the notebook:

```
fn = download_file('https://stsci.box.com/s/pu9vh5y2hw0gz984izvkc8jrzy8qj795')
specviz.load_spectrum(fn, data_label="Demo SDSS", format="SDSS-III/IV spec")
```

I get `OSError: Empty or corrupt FITS file`. Any clue as to where I might have gone wrong in the Box setup? I can download the file manually from Box and confirmed that astropy.io.fits can open it.

**Comment by cslocum** [comment]
image

**Comment by rosteen** [comment]
@cslocum that particular error message is something I can fix, but it should only happen if you try to load the same data twice. Can you confirm that that's the case where you saw the error?

**Comment by rosteen** [comment]
Created a PR in jdaviz to fix that: https://github.com/spacetelescope/jdaviz/pull/568

**Review by eteq — COMMENTED** [review]
After some out-of-band discussion @camipacifici and I realized we want a `requirements.txt` so that people who grab this notebook *outside* of the webbinar know what they need to have installed.  So can you add a `requirements.txt` a la https://github.com/spacetelescope/jwebbinar_prep/pull/13/commits/ac38da055d98161e0e99ce055c222a94b72b129b ?

(It will conflict with the other PRs but there's no helping that, so we'll just have to merge-as-we-go :shrug: )

**Comment by camipacifici** [comment]
Looks great! I really like the idea of having beginner and advanced for the exercises.
Same comment as for @eteq to use JWST simulated data or some model here. @PatrickOgle might have something for you.

**Comment by cslocum** [comment]
> @cslocum that particular error message is something I can fix, but it should only happen if you try to load the same data twice. Can you confirm that that's the case where you saw the error?

I did run it twice.  The first time I selected "run all cells", and after the kernel indicated it was idle, I noticed that that particular cell had not been run.  So I ran just that one and got the error.

I suggest maybe adding a check in there to see if the file already exists?  (or at least I think that would fix it/make it more robust.)

**Comment by camipacifici** [comment]
@rosteen 
Tested the notebook, looks good and works fine. A few things still needed:
- Use the spectrum by Patrick (have you solved the problems with the box link?)...I am afraid you will need to change all the limits and regions...
- Provide the "live" notebook that you will be using to live code during the webinar. Here is an example: https://github.com/spacetelescope/jwebbinar_prep/blob/main/pipeline_products_session/jwst-data-products-part1-live.ipynb
- Please provide solutions to the exercises at the end of the notebook.

**Comment by rosteen** [comment]
Updated, I think the last thing I'm likely to do is write some more detailed notes on the solutions to the exercises.

**Comment by rosteen** [comment]
I think this is done! Just added detailed solutions to the exercises to the end of the _solutions notebook.

**Pull request merged**
