### PR TITLE
Initial commit of MRS Notebook 1

### PR DESCRIPTION
**Pull request by drlaw1558**

### CODE REVIEW

**Comment by cslocum** [comment]
David - Has notebook 1 been testing with the data files that are currently on the platform?

**Comment by cslocum** [comment]
@drlaw1558 - these files should be moved into the `ers` directory you created in you latest PR.

**Comment by drlaw1558** [comment]
Should they be in ers/ or spec_mode/mirimrs?  Notebook 2 will be part of the ERS presentation, but will also be part of the regular JWebbinar #5 (possibly with some changes by that point in time), and Notebook 1 will be part of JWebbinar #4.

**Comment by drlaw1558** [comment]
And yes, both have been tested with a manual load.

**Comment by cslocum** [comment]
Hmm, @camipacifici do you have any thoughts here?

> Should they be in ers/ or spec_mode/mirimrs? Notebook 2 will be part of the ERS presentation, but will also be part of the regular JWebbinar #5 (possibly with some changes by that point in time), and Notebook 1 will be part of JWebbinar #4.

**Comment by camipacifici** [comment]
@drlaw1558 is this the final version for the ers webinar?
I think it is ok to leave them in spec_mode/mirimrs because you might make changes for JWebbinar 4. I will make a copy in the ers folder for the ers webinar, if this is your final version for June 3.

**Comment by camipacifici** [comment]
@drlaw1558 just to make sure I understand. I thought this notebook was also for the ERS presentation, but maybe it is not? Please, confirm that this will NOT be part of the presentation on June 3.
Thank you!

**Comment by drlaw1558** [comment]
@camipacifici Notebook2 as committed via PR#31 lives at /ers/ and will be the notebook that I show during the ERS presentation.  Notebook1 and Notebook2 as committed to the spec_mode/mirimrs/ in the PR#28 will *not* be part of the ERS presentation, but are for the regular Series #4 and Series #5 respectively.

**Pull request merged**
